-- both test users have the password "password"

INSERT INTO users (username, name, email, password, profile_pic, is_admin)
VALUES ('testadmin',
        'testname1',
        'testadmin@gmail.com',
        '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q',
        'http://localhost:3001/images/testadmin.png',
        TRUE),
        ('testuser1',
        'testname2',
        'testuser1@gmail.com',
        '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q',
        'http://localhost:3001/images/testuser1.png',
        FALSE),
        ('testuser2',
        'testname3',
        'testuser2@gmail.com',
        '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q',
        'http://localhost:3001/images/testuser2.png',
        FALSE),
         ('testadmin2', 
          'Admin User',
          'admin@example.com',
          '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q',
          'http://localhost:3001/images/testadmin2.png', 
           TRUE),
        ('alice',     
        'Alice Smith', 
        'alice@example.com', 
        '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q', 
        'http://localhost:3001/images/alice.jpg', 
        FALSE),
        ('bob',       
        'Bob Johnson', 
        'bob@example.com',   
        '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q', 
        'http://localhost:3001/images/bob.png', 
        FALSE),
        ('carol',     
        'Carol Williams', 
        'carol@example.com', 
        '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q', 
        'http://localhost:3001/images/carol.png', 
        FALSE),
        ('dave',      
        'Dave Brown', 
        'dave@example.com',   
        '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q', 
        'http://localhost:3001/images/dave.jpg', 
        FALSE);


INSERT INTO pets (name,
                  type,
                  breed,
                  age,
                  bio,
                  photo_url,
                  owner_id)

VALUES
  ('Luna',    'Dog', 'Shih-poo',         2, 'Loves to play fetch.',           'http://localhost:3001/images/Luna.jpg', 1),
  ('Leo',    'Dog', 'Maltipoo',         2, 'Loves to play fetch.',           'http://localhost:3001/images/Leo.jpg', 1),
  ('Max',     'Dog', 'Labrador',         3, 'Enjoys swimming.',                 'http://localhost:3001/images/Max.png', 2),
  ('Bella',   'Cat', 'Siamese',          1, 'Curious and playful.',             'http://localhost:3001/images/Bella.png', 3),
  ('Charlie', 'Dog', 'Beagle',           4, 'Friendly and active.',             'http://localhost:3001/images/Charlie.jpg', 4),
  ('Lucy',    'Cat', 'Persian',          5, 'Loves napping in the sun.',        'http://localhost:3001/images/Lucy.png', 5),
  ('Rocky',   'Dog', 'Bulldog',          6, 'Chill and loves treats.',          'http://localhost:3001/images/Rocky.jpg', 6),
  ('Daisy',   'Cat', 'Maine Coon',       3, 'Gentle and loving.',               'http://localhost:3001/images/Daisy.jpg', 2),
  ('Buddy',   'Dog', 'Poodle',           2, 'Energetic and smart.',             'http://localhost:3001/images/Buddy.jpg', 7),
  ('Molly',   'Cat', 'Ragdoll',          4, 'Calm and affectionate.',           'http://localhost:3001/images/Molly.jpg', 4),
  ('Bailey',  'Dog', 'German Shepherd',  3, 'Loyal and protective.',            'http://localhost:3001/images/Bailey.png', 8);


INSERT INTO posts (content,
                  image_url,
                  owner_id,
                  created_at)
VALUES
  ('Leo and Luna are best friends.',                'http://localhost:3001/images/post0.jpg', 1, NOW() - INTERVAL '1 hours'),
  ('Enjoying a sunny day with my pet Luna!',        'http://localhost:3001/images/post1.jpg',  1, NOW() - INTERVAL '1 day'),
  ('Max had a great time at the park!',              'http://localhost:3001/images/post2.jpg',                              2, NOW() - INTERVAL '20 hours'),
  ('Bella is so playful today!',                        'http://localhost:3001/images/post3.jpg',  3, NOW() - INTERVAL '18 hours'),
  ('Charlie loves his new toy.',                        'http://localhost:3001/images/post4.jpg',  4, NOW() - INTERVAL '16 hours'),
  ('Lucy is taking a nap in the sun.',                  NULL,                             5, NOW() - INTERVAL '14 hours'),
  ('Rocky just learned a new trick.',                   'http://localhost:3001/images/post6.jpg',  1, NOW() - INTERVAL '12 hours'),
  ('Daisy''s curiosity knows no bounds.',              NULL,                             2, NOW() - INTERVAL '10 hours'),
  ('Buddy is super smart!',                             'http://localhost:3001/images/post8.jpeg',  3, NOW() - INTERVAL '8 hours'),
  ('Molly is enjoying her day.',                        NULL,                             4, NOW() - INTERVAL '6 hours'),
  ('Bailey is always alert and active.',                'http://localhost:3001/images/post10.jpg', 5, NOW() - INTERVAL '4 hours'),
  ('Luna had a fun with snow today.',                    'http://localhost:3001/images/post11.jpg', 1, NOW() - INTERVAL '2 days'),
  ('Max showed off his swimming skills.',             NULL,                             2, NOW() - INTERVAL '1 day'),
  ('Bella is enjoying a quiet afternoon.',              'http://localhost:3001/images/post13.jpg', 3, NOW() - INTERVAL '20 hours'),
  ('Charlie took a long walk.',                         NULL,                             4, NOW() - INTERVAL '18 hours'),
  ('Lucy is exploring the neighborhood.',              'http://localhost:3001/images/post15.jpg', 5, NOW() - INTERVAL '16 hours'),
  ('Rocky is munching on his favorite treat.',         NULL,                             1, NOW() - INTERVAL '14 hours'),
  ('Daisy is getting into mischief again.',            'http://localhost:3001/images/post17.jpg', 2, NOW() - INTERVAL '12 hours'),
  ('Buddy enjoyed a fun game of fetch.',               NULL,                             3, NOW() - INTERVAL '10 hours'),
  ('Molly is the queen of relaxation.',                'http://localhost:3001/images/post19.jpg', 4, NOW() - INTERVAL '8 hours'),
  ('Bailey is showing off his skills at agility.',     NULL,                             5, NOW() - INTERVAL '6 hours'),
  ('Luna and Rocky had a play session.',               'http://localhost:3001/images/post21.jpg', 1, NOW() - INTERVAL '5 hours'),
  ('Max and Bailey went for a run.',                   NULL,                             2, NOW() - INTERVAL '4 hours'),
  ('Bella and Daisy are best friends.',                'http://localhost:3001/images/post23.jpg', 3, NOW() - INTERVAL '3 hours'),
  ('Charlie is training for a competition.',           NULL,                             4, NOW() - INTERVAL '2 hours'),
  ('Lucy had a peaceful day at home.',                 'http://localhost:3001/images/post25.png', 5, NOW() - INTERVAL '1 hour'),
  ('Leo had a fun with travel today.',                 'http://localhost:3001/images/post26.jpg', 1, NOW() - INTERVAL '2 days'),
  ('Leo and Luna are playing together.',               'http://localhost:3001/images/post27.jpg', 1, NOW() - INTERVAL '1 hours');


INSERT INTO comments (post_id,
                      owner_id,
                      content,
                      created_at)
VALUES
  (1, 2, 'Awesome photo!',           NOW() - INTERVAL '11 hours'),
  (1, 3, 'So cute!',                NOW() - INTERVAL '10 hours'),
  (2, 1, 'Great post!',             NOW() - INTERVAL '9 hours'),
  (2, 4, 'Love it!',                NOW() - INTERVAL '8 hours'),
  (3, 5, 'Fantastic!',              NOW() - INTERVAL '7 hours'),
  (3, 2, 'So playful!',             NOW() - INTERVAL '6 hours'),
  (4, 3, 'Adorable!',               NOW() - INTERVAL '5 hours'),
  (4, 1, 'Looks fun!',              NOW() - INTERVAL '4 hours'),
  (5, 4, 'Cute cat!',               NOW() - INTERVAL '3 hours'),
  (5, 2, 'Lovely!',                 NOW() - INTERVAL '2 hours'),
  (6, 5, 'Impressive trick!',       NOW() - INTERVAL '1 hour'),
  (6, 3, 'Well done!',              NOW() - INTERVAL '50 minutes'),
  (7, 1, 'Cute and curious!',       NOW() - INTERVAL '45 minutes'),
  (7, 2, 'Amazing!',                NOW() - INTERVAL '40 minutes'),
  (8, 4, 'So smart!',               NOW() - INTERVAL '35 minutes'),
  (8, 5, 'Incredible!',             NOW() - INTERVAL '30 minutes'),
  (9, 1, 'Great day!',              NOW() - INTERVAL '25 minutes'),
  (9, 3, 'Love this!',              NOW() - INTERVAL '20 minutes'),
  (10, 2, 'Awesome agility!',       NOW() - INTERVAL '15 minutes'),
  (10, 4, 'Well done!',             NOW() - INTERVAL '10 minutes'),
  (11, 5, 'So playful!',            NOW() - INTERVAL '9 minutes'),
  (11, 2, 'Fun time!',              NOW() - INTERVAL '8 minutes'),
  (12, 3, 'Beautiful!',             NOW() - INTERVAL '7 minutes'),
  (12, 1, 'Great post!',            NOW() - INTERVAL '6 minutes'),
  (13, 4, 'So cute!',               NOW() - INTERVAL '5 minutes'),
  (13, 5, 'Lovely!',                NOW() - INTERVAL '4 minutes'),
  (14, 2, 'Interesting!',           NOW() - INTERVAL '3 minutes'),
  (14, 3, 'Wow!',                   NOW() - INTERVAL '2 minutes'),
  (15, 1, 'So sweet!',              NOW() - INTERVAL '1 minute'),
  (15, 4, 'Adorable!',              NOW()),
  (16, 2, 'Impressive!',            NOW() - INTERVAL '1 hour'),
  (16, 3, 'Fantastic trick!',       NOW() - INTERVAL '50 minutes'),
  (17, 5, 'Very cute!',             NOW() - INTERVAL '45 minutes'),
  (17, 1, 'Great skills!',          NOW() - INTERVAL '40 minutes'),
  (18, 2, 'Nice game!',             NOW() - INTERVAL '35 minutes'),
  (18, 4, 'Well played!',           NOW() - INTERVAL '30 minutes'),
  (19, 3, 'So relaxing!',           NOW() - INTERVAL '25 minutes'),
  (19, 1, 'Looks peaceful!',        NOW() - INTERVAL '20 minutes'),
  (20, 5, 'Amazing agility!',       NOW() - INTERVAL '15 minutes'),
  (20, 2, 'Very active!',           NOW() - INTERVAL '10 minutes');


INSERT INTO likes (post_id,
                    owner_id)  
VALUES
  (1, 2),
  (1, 3),
  (1, 4),
  (2, 1),
  (2, 3),
  (2, 5),
  (3, 2),
  (3, 4),
  (3, 5),
  (4, 1),
  (4, 2),
  (4, 5),
  (5, 1),
  (5, 3),
  (5, 4),
  (6, 2),
  (6, 3),
  (6, 4),
  (7, 1),
  (7, 3),
  (7, 5),
  (8, 2),
  (8, 4),
  (8, 5),
  (9, 1),
  (9, 2),
  (9, 3),
  (10, 4),
  (10, 5),
  (10, 1),
  (11, 2),
  (11, 3),
  (11, 4),
  (12, 1),
  (12, 5),
  (12, 2),
  (13, 3),
  (13, 4),
  (13, 5),
  (14, 1),
  (14, 2),
  (14, 3),
  (15, 4),
  (15, 5),
  (15, 1),
  (16, 2),
  (16, 3),
  (16, 4),
  (17, 5),
  (17, 1);


INSERT INTO events (title,
                    description,
                    location,
                    date,
                    start_time,
                    end_time,
                    created_by,
                    lat,
                    lng)
VALUES
  ('Dog Walk Meetup', 'Join us for a dog walk in the park.', 'Central Park, NYC', NOW() + INTERVAL '5 days', '10:00:00', '12:00:00', 1, 40.785091, -73.968285),
  ('Cat Lovers Gathering', 'A fun meetup for cat enthusiasts.', 'Downtown Cafe, NYC', NOW() + INTERVAL '7 days', '14:00:00', '16:00:00', 2, 40.712776, -74.005974),
  ('Puppy Playdate', 'Bring your puppies for a play session.', 'Brooklyn Bridge Park, NYC', NOW() + INTERVAL '3 days', '11:00:00', '13:00:00', 3, 40.700292, -73.987495),
  ('Pet Training Workshop', 'Learn training tips for your pets.', 'Animal Care Center, NYC', NOW() + INTERVAL '10 days', '09:00:00', '11:00:00', 4, 40.730610, -73.935242),
  ('Dog Agility Competition', 'Compete in a fun dog agility contest.', 'Madison Square Garden, NYC', NOW() + INTERVAL '15 days', '12:00:00', '14:00:00', 5, 40.750504, -73.993439),
  ('Pet Costume Party', 'Dress up your pet and join the fun.', 'Riverside Park, NYC', NOW() + INTERVAL '6 days', '17:00:00', '19:00:00', 1, 40.800678, -73.958000),
  ('Cat Agility Show', 'Watch cats compete in agility challenges.', 'Cat Cafe, NYC', NOW() + INTERVAL '8 days', '15:00:00', '17:00:00', 2, 40.728226, -73.794853),
  ('Pet Adoption Fair', 'Meet pets looking for a home.', 'Community Center, NYC', NOW() + INTERVAL '4 days', '10:00:00', '12:00:00', 3, 40.712217, -74.016058),
  ('Pet Health Seminar', 'Learn about pet nutrition and health.', 'Veterinary Clinic, NYC', NOW() + INTERVAL '9 days', '13:00:00', '15:00:00', 4, 40.712776, -73.998672),
  ('Evening Pet Walk', 'Join an evening walk with your pet.', 'Prospect Park, NYC', NOW() + INTERVAL '2 days', '18:00:00', '20:00:00', 5, 40.660204, -73.969780);


INSERT INTO notifications (user_id, 
                          type, 
                          content, 
                          is_read, 
                          created_at)

VALUES
  (1, 'like',           'Your post has a new like!',           FALSE, CURRENT_TIMESTAMP),
  (2, 'comment',        'Someone commented on your post!',        FALSE, CURRENT_TIMESTAMP),
  (5, 'like',           'Your post has a new like!',           FALSE, CURRENT_TIMESTAMP),
  (1, 'comment',        'Someone commented on your post!',        FALSE, CURRENT_TIMESTAMP),
  (4, 'like',           'Your post has a new like!',           FALSE, CURRENT_TIMESTAMP),
  (5, 'comment',        'New comment on your post!',              FALSE, CURRENT_TIMESTAMP);     